services:

### Client ###

  Andreo\GuzzleBundle\Client\ClientFactory:

  Andreo\GuzzleBundle\Client\ClientFactoryInterface:
    alias: Andreo\GuzzleBundle\Client\ClientFactory

### DataTransfer ###

  andreo.guzzle.normalizer.object:
    arguments:
      - null
      - '@serializer.name_converter.camel_case_to_snake_case'

  andreo.guzzle.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - ['@andreo.guzzle.normalizer.object']
      - ['@serializer.encoder.json']

  andreo.guzzle.json_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags: [andreo.guzzle.data_mapper]
    arguments:
      - '@andreo.guzzle.serializer'
      - 'json'

  andreo.guzzle.xml_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags: [andreo.guzzle.data_mapper]
    arguments:
      - '@andreo.guzzle.serializer'
      - 'xml'

  Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry:
    arguments:
      - !tagged_iterator andreo.guzzle.data_mapper

  ### Middleware ###

  Andreo\GuzzleBundle\Middleware\MiddlewareRegistry:
    arguments:
      - !tagged_iterator andreo.guzzle.middleware

  Andreo\GuzzleBundle\Middleware\TransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    lazy: true
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry'

  Andreo\GuzzleBundle\Middleware\ReverseTransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    lazy: true
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry'

  Andreo\GuzzleBundle\Middleware\MiddlewareRegistryInterface:
    alias: Andreo\GuzzleBundle\Middleware\MiddlewareRegistry


