services:

### Client ###

  Andreo\GuzzleBundle\Client\ClientFactory:

  Andreo\GuzzleBundle\Client\ClientFactoryInterface:
    alias: Andreo\GuzzleBundle\Client\ClientFactory

### Configurator ###

  Andreo\GuzzleBundle\Configurator\Configurator:
    shared: false
    arguments:
      - !tagged_iterator andreo.guzzle.delegating_configurator

  Andreo\GuzzleBundle\Configurator\ConfiguratorInterface:
    alias: Andreo\GuzzleBundle\Configurator\Configurator

  ### Middleware ###

  Andreo\GuzzleBundle\Middleware\MiddlewareStorage:
    arguments:
      - !tagged_iterator andreo.guzzle.middleware

  Andreo\GuzzleBundle\Middleware\MiddlewareStorageInterface:
    alias: Andreo\GuzzleBundle\Middleware\MiddlewareStorage
