services:

### Client ###

  Andreo\GuzzleBundle\Client\ClientFactory:

  Andreo\GuzzleBundle\Client\ClientFactoryInterface:
    alias: Andreo\GuzzleBundle\Client\ClientFactory

### Configurator ###

  Andreo\GuzzleBundle\Configurator\ConfigurationFactory:
    arguments:
      - !tagged_iterator andreo.guzzle.middleware

  Andreo\GuzzleBundle\Configurator\ConfiguratorFactoryInterface:
    alias: Andreo\GuzzleBundle\Configurator\ConfigurationFactory

### DataTransfer ###

  andreo.guzzle.normalizer.object:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - null
      - '@serializer.name_converter.camel_case_to_snake_case'

  andreo.guzzle.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - ['@andreo.guzzle.normalizer.object']
      - ['@serializer.encoder.json']

  andreo.guzzle.json_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags:
      - { name: 'andreo.guzzle.data_mapper', key: 'json' }
    arguments:
      - '@andreo.guzzle.serializer'
      - 'json'

  andreo.guzzle.xml_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags:
      - { name: 'andreo.guzzle.data_mapper', key: 'xml' }
    arguments:
      - '@andreo.guzzle.serializer'
      - 'xml'

  Andreo\GuzzleBundle\DataTransfer\DataMapperLocator:
    arguments: [!tagged_locator { tag: 'andreo.guzzle.data_mapper', index_by: 'key' }]

### Middleware ###

  Andreo\GuzzleBundle\Middleware\TransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    lazy: true
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperLocator'

  Andreo\GuzzleBundle\Middleware\ReverseTransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    lazy: true
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperLocator'
