services:

### Client ###

  Andreo\GuzzleBundle\Client\ClientFactory:

  Andreo\GuzzleBundle\Client\ClientFactoryInterface:
    alias: Andreo\GuzzleBundle\Client\ClientFactory

### Configurator ###

  Andreo\GuzzleBundle\Configurator\Configurator:
    shared: false

  Andreo\GuzzleBundle\Configurator\ConfiguratorInterface:
    alias: Andreo\GuzzleBundle\Configurator\Configurator

### DataTransfer ###

  andreo.guzzle.json_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags: [andreo.guzzle.data_mapper]
    arguments:
      - '@serializer'
      - 'json'

  andreo.guzzle.xml_data_mapper:
    class: Andreo\GuzzleBundle\DataTransfer\DataMapper
    lazy: true
    tags: [andreo.guzzle.data_mapper]
    arguments:
      - '@serializer'
      - 'xml'

  Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry:
    arguments:
      - !tagged_iterator andreo.guzzle.data_mapper

  ### Middleware ###

  Andreo\GuzzleBundle\Middleware\MiddlewareRegistry:
    arguments:
      - !tagged_iterator andreo.guzzle.middleware

  Andreo\GuzzleBundle\Middleware\TransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry'

  Andreo\GuzzleBundle\Middleware\ReverseTransferDataMiddleware:
    tags: [andreo.guzzle.middleware]
    arguments:
      - '@Andreo\GuzzleBundle\DataTransfer\DataMapperRegistry'

  Andreo\GuzzleBundle\Middleware\MiddlewareRegistryInterface:
    alias: Andreo\GuzzleBundle\Middleware\MiddlewareRegistry


